# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='spot_id',
            field=models.IntegerField(default=0),
        ),
    ]
