# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160504_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lat_long',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
