# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.CharField(default=b'[]', max_length=200),
        ),
    ]
